apiVersion: v2
appVersion: v2.2.5
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 3.35.0
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
dependencies:
  - name: redis-ha
    version: 4.10.4
    repository: "file://../redis-ha"
    condition: redis-ha.enabled
annotations:
  artifacthub.io/changes: |
    - "[Added]: Expose 'clusterResources' parameter in configs.clusterCredentials"
