server:
  configEnabled: true
  config:
    repositories: |
      - type: git
        url: https://github.com/paas2/security-infra-apps.git 
      - type: git
        url: https://github.com/paas2/security-apps.git            
  additionalApplications: 
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ./values-security-dev.yaml
        path: helm-charts/argocd
        repoURL: https://github.com/paas2/argocd.git 
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true       

    - name: infra-apps  
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: dev/apps
        repoURL: https://github.com/paas2/security-infra-apps.git 
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true  
          
    - name: infra-app-projects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: dev/projects
        repoURL: https://github.com/paas2/security-infra-apps.git  
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true          

    - name: securiy-apps
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml 
        path: dev/apps
        repoURL: https://github.com/paas2-security/secyurity-apps.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true    

    - name: security-app-projects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: dev/projects
        repoURL: https://github.com/paas2/security-apps.git  
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          
  additionalProjects: 
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false